### ISSUE TITLE
* client_ip in tabel session klopt niet is 56.54.46.56 ipv ip van client

### ISSUE THREAD

**Issue by JvGinkel** [mpdroog/radiusd#1]
# radiusd -v -d output:
radiusd 2015/11/09 19:37:28 packet.decode: &{secret:vpnxs1234 Code:1 Identifier:9 Len:117 Auth:[35 142 31 41 70 232 124 205 61 27 88 186 80 126 215 171] Attrs:map[6:{Type:6 Length:6 Value:[0 0 0 2]} 7:{Type:7 Length:6 Value:[0 0 0 1]} 1:{Type:1 Length:9 Value:[109 101 108 107 109 97 110]} 32:{Type:32 Length:10 Value:[77 105 107 114 111 84 105 107]} 5:{Type:5 Length:6 Value:[0 0 1 205]} 61:{Type:61 Length:6 Value:[0 0 0 5]} 31:{Type:31 Length:15 Value:[56 54 46 56 57 46 50 51 51 46 49 50 57]} 30:{Type:30 Length:15 Value:[49 55 56 46 50 48 46 49 55 53 46 50 51]} 2:{Type:2 Length:18 Value:[49 255 48 146 58 84 231 2 155 223 101 100 27 65 1 31]} 4:{Type:4 Length:6 Value:[178 20 175 23]}]}
radiusd 2015/11/09 19:37:28 auth user=melkman pass=melkman
radiusd 2015/11/09 19:37:28 packet.encode: [2 9 0 26 35 142 31 41 70 232 124 205 61 27 88 186 80 126 215 171 62 6 0 0 0 1]
radiusd 2015/11/09 19:37:28 packet.decode: &{secret:vpnxs1234 Code:4 Identifier:10 Len:139 Auth:[28 13 3 164 35 185 206 185 198 237 247 28 100 66 160 130] Attrs:map[6:{Type:6 Length:6 Value:[0 0 0 2]} 5:{Type:5 Length:6 Value:[0 0 1 205]} 4:{Type:4 Length:6 Value:[178 20 175 23]} 7:{Type:7 Length:6 Value:[0 0 0 1]} 61:{Type:61 Length:6 Value:[0 0 0 5]} 1:{Type:1 Length:9 Value:[109 101 108 107 109 97 110]} 45:{Type:45 Length:6 Value:[0 0 0 1]} 41:{Type:41 Length:6 Value:[0 0 0 0]} 31:{Type:31 Length:15 Value:[56 54 46 56 57 46 50 51 51 46 49 50 57]} 30:{Type:30 Length:15 Value:[49 55 56 46 50 48 46 49 55 53 46 50 51]} 8:{Type:8 Length:6 Value:[192 168 124 95]} 40:{Type:40 Length:6 Value:[0 0 0 1]} 32:{Type:32 Length:10 Value:[77 105 107 114 111 84 105 107]} 44:{Type:44 Length:10 Value:[56 49 52 48 48 48 49 57]} 55:{Type:55 Length:6 Value:[0 181 9 211]}]}
radiusd 2015/11/09 19:37:28 acct.begin sess=81400019 for user=melkman on nasIP=178.20.175.23
radiusd 2015/11/09 19:37:28 packet.encode: [5 10 0 20 28 13 3 164 35 185 206 185 198 237 247 28 100 66 160 130]

# Mikrotik radius debug log

Nov  9 19:35:56 178.20.175.23 radius,debug new request 1b:85 code=Access-Request service=ppp called-id=178.20.175.23
Nov  9 19:35:56 178.20.175.23 radius,debug sending 1b:85 to 178.20.175.153:1812
Nov  9 19:35:56 178.20.175.23 radius,debug,packet sending Access-Request with id 9 to 178.20.175.153:1812
Nov  9 19:35:56 178.20.175.23 radius,debug,packet     Signature = 0x238e1f2946e87ccd3d1b58ba507ed7ab
Nov  9 19:35:56 178.20.175.23 radius,debug,packet     Service-Type = 2
Nov  9 19:35:56 178.20.175.23 radius,debug,packet     Framed-Protocol = 1
Nov  9 19:35:56 178.20.175.23 radius,debug,packet     NAS-Port = 461
Nov  9 19:35:56 178.20.175.23 radius,debug,packet     NAS-Port-Type = 5
Nov  9 19:35:56 178.20.175.23 radius,debug,packet     User-Name = "melkman"
Nov  9 19:35:56 178.20.175.23 radius,debug,packet     Calling-Station-Id = "86.89.233.129"
Nov  9 19:35:56 178.20.175.23 radius,debug,packet     Called-Station-Id = "178.20.175.23"
Nov  9 19:35:56 178.20.175.23 radius,debug,packet     User-Password = 0x6d656c6b6d616e
Nov  9 19:35:56 178.20.175.23 radius,debug,packet     NAS-Identifier = "MikroTik"
Nov  9 19:35:56 178.20.175.23 radius,debug,packet     NAS-IP-Address = 178.20.175.23
Nov  9 19:35:56 178.20.175.23 radius,debug,packet received Access-Accept with id 9 from 178.20.175.153:1812
Nov  9 19:35:56 178.20.175.23 radius,debug,packet     Signature = 0x95029d00faf86e71a799f4001ff0e807
Nov  9 19:35:56 178.20.175.23 radius,debug,packet     Port-Limit = 1
Nov  9 19:35:56 178.20.175.23 radius,debug received reply for 1b:85
Nov  9 19:35:56 178.20.175.23 radius,debug new request 1b:00 code=Accounting-Request service=ppp called-id=178.20.175.23
Nov  9 19:35:56 178.20.175.23 radius,debug sending 1b:00 to 178.20.175.153:1813
Nov  9 19:35:56 178.20.175.23 radius,debug,packet sending Accounting-Request with id 10 to 178.20.175.153:1813
Nov  9 19:35:56 178.20.175.23 radius,debug,packet     Signature = 0x1c0d03a423b9ceb9c6edf71c6442a082
Nov  9 19:35:56 178.20.175.23 radius,debug,packet     Service-Type = 2
Nov  9 19:35:56 178.20.175.23 radius,debug,packet     Framed-Protocol = 1
Nov  9 19:35:56 178.20.175.23 radius,debug,packet     NAS-Port = 461
Nov  9 19:35:56 178.20.175.23 radius,debug,packet     NAS-Port-Type = 5
Nov  9 19:35:56 178.20.175.23 radius,debug,packet     User-Name = "melkman"
Nov  9 19:35:56 178.20.175.23 radius,debug,packet     Calling-Station-Id = "86.89.233.129"
Nov  9 19:35:56 178.20.175.23 radius,debug,packet     Called-Station-Id = "178.20.175.23"
Nov  9 19:35:56 178.20.175.23 radius,debug,packet     Acct-Session-Id = "81400019"
Nov  9 19:35:56 178.20.175.23 radius,debug,packet     Framed-IP-Address = 192.168.124.95
Nov  9 19:35:56 178.20.175.23 radius,debug,packet     Acct-Authentic = 1
Nov  9 19:35:56 178.20.175.23 radius,debug,packet     Event-Timestamp = 11864531
Nov  9 19:35:56 178.20.175.23 radius,debug,packet     Acct-Status-Type = 1
Nov  9 19:35:56 178.20.175.23 radius,debug,packet     NAS-Identifier = "MikroTik"
Nov  9 19:35:56 178.20.175.23 radius,debug,packet     Acct-Delay-Time = 0
Nov  9 19:35:56 178.20.175.23 radius,debug,packet     NAS-IP-Address = 178.20.175.23
Nov  9 19:35:56 178.20.175.23 radius,debug,packet received Accounting-Response with id 10 from 178.20.175.153:1813
Nov  9 19:35:56 178.20.175.23 radius,debug,packet     Signature = 0x8951efaf9284e7e1d249a0e2706920b5
Nov  9 19:35:56 178.20.175.23 radius,debug received reply for 1b:00
Nov  9 19:35:56 178.20.175.23 radius,debug request 1b:00 processed

# SQL:
('81400019', 'melkman', '178.20.175.23', 0, 0, 0, 0, 0, '**56.54.46.56**', '192.168.124.95', 1447094248);

**Comment by mpdroog** [comment]
c37e2af
