### ISSUE TITLE
CoA request.

### ISSUE THREAD

**Issue by parsibox** [mpdroog/radiusd#10]
hi
can we send CoA request.?

**Comment by mpdroog** [comment]
Hi,

I'm assuming you mean "Change of Authorization with RADIUS (CoA)", that feature is currently not implemented.

**Comment by parsibox** [comment]
> Hi,
> 
> I'm assuming you mean "Change of Authorization with RADIUS (CoA)", that feature is currently not implemented.

yes also i want to disconnect user or change rate

**Comment by mpdroog** [comment]
Not implemented, feel free to add it.
