### ISSUE TITLE
simultaneous_use werkt niet

### ISSUE THREAD

**Issue by JvGinkel** [mpdroog/radiusd#4]
Als deze op 1 staat en er is al 1 connectie dan kan er een 2de connectie gemaakt worden. De Access-Request word gewoon geaccepteerd:

Nov  9 20:21:58 178.20.175.23 radius,debug new request 1b:9a code=Access-Request service=ppp called-id=178.20.175.23
Nov  9 20:21:58 178.20.175.23 radius,debug sending 1b:9a to 178.20.175.153:1812
Nov  9 20:21:58 178.20.175.23 radius,debug,packet sending Access-Request with id 50 to 178.20.175.153:1812
Nov  9 20:21:58 178.20.175.23 radius,debug,packet     Signature = 0x08edbdab79838cb24353d0cd0b03e0c6
Nov  9 20:21:58 178.20.175.23 radius,debug,packet     Service-Type = 2
Nov  9 20:21:58 178.20.175.23 radius,debug,packet     Framed-Protocol = 1
Nov  9 20:21:58 178.20.175.23 radius,debug,packet     NAS-Port = 405
Nov  9 20:21:58 178.20.175.23 radius,debug,packet     NAS-Port-Type = 5
Nov  9 20:21:58 178.20.175.23 radius,debug,packet     User-Name = "melkman"
Nov  9 20:21:58 178.20.175.23 radius,debug,packet     Calling-Station-Id = "86.89.233.129"
Nov  9 20:21:58 178.20.175.23 radius,debug,packet     Called-Station-Id = "178.20.175.23"
Nov  9 20:21:58 178.20.175.23 radius,debug,packet     User-Password = 0x6d656c6b6d616e
Nov  9 20:21:58 178.20.175.23 radius,debug,packet     NAS-Identifier = "MikroTik"
Nov  9 20:21:58 178.20.175.23 radius,debug,packet     NAS-IP-Address = 178.20.175.23
Nov  9 20:21:58 178.20.175.23 radius,debug,packet received Access-Accept with id 50 from 178.20.175.153:1812
Nov  9 20:21:58 178.20.175.23 radius,debug,packet     Signature = 0xa29da47bfe20056e0cf893d261d54500
Nov  9 20:21:58 178.20.175.23 radius,debug,packet     Port-Limit = 0
Nov  9 20:21:58 178.20.175.23 radius,debug received reply for 1b:9a

**Comment by mpdroog** [comment]
86f159c5889a7c9d8110681860f4d47f7fcf9819
